environment_name: lab
release_branch: develop

ansible_python_interpreter: auto_silent
default_packages:
   - cron
   - gcc
   - git
   - make
   - mergerfs
   - parted
   - python3-pip
   - screen
   - smartmontools

install_ssh_keys: no
