environment_name: lab

ansible_python_interpreter: auto_silent
default_packages:
   - cron
   - gcc
   - git
   - make
   - mergerfs
   - parted
   - python3-pip
   - screen
   - smartmontools

snapraid_release: 12.2
snapraid_url: "https://github.com/amadvance/snapraid/releases/download/v{{ snapraid_release }}/snapraid-{{ snapraid_release }}.tar.gz"
snapraid_build_path: /var/tmp/snapraid

install_ssh_keys: no

k3s_build_cluster: no
k3s_become: yes

kubeconf_local_path: /tmp/kubeconfig

device_paths:  # TODO: Make sure these are correct when rebuilding the old system
  - "pci-0000:00:1f.2-ata-2"
  - "pci-0000:00:1f.2-ata-4"
  - "pci-0000:00:1f.2-ata-6"

htpc_root: "/opt/htpc"
media_mount_path: "{{ htpc_root }}/media"
media_storage_paths:
  - "{{ media_mount_path }}/tv"
  - "{{ media_mount_path }}/movies"
media_pool_disks:
  - "/mnt/pools/media/disks/0"
  - "/mnt/pools/media/disks/1"
media_parity_disks:
  - "/mnt/pools/media/parity"
media_pool_paths: "{{ media_pool_disks + media_parity_disks }}"

logrotate_scripts:
  - name: snapraid-sync
    path: "/var/log/snapraid/sync.log"
    options:
      - daily
      - rotate 10
      - missingok
      - compress
      - copytruncate
      - delaycompress
  - name: snapraid-scrub
    path: "/var/log/snapraid/scrub.log"
    options:
      - weekly
      - rotate 10
      - missingok
      - compress
      - copytruncate
      - delaycompress

htk8s_repo_release: v0.1.0
